--RaceDay Database Script
-- PROG6212 POE
--Koketso Modiselle 

CREATE DATABASE RaceDay;
GO

USE RaceDay;
GO



-- USER TABLE
CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL DEFAULT 'Participant'
);

 ORGANISER TABLE
CREATE TABLE Organiser (
    OrganiserID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    OrganisationName VARCHAR(100) NOT NULL,
    ContactNumber VARCHAR(20) NOT NULL UNIQUE,

    CONSTRAINT FK_Organiser_User
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);


-- PARTICIPANT TABLE
CREATE TABLE Participant (
    ParticipantID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    DateOfBirth DATE NOT NULL,

    CONSTRAINT FK_Participant_User
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

- CATEGORY TABLE
CREATE TABLE Category (
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL UNIQUE,
    DistanceKM DECIMAL(5,2) NOT NULL
);
